# -*- coding: utf-8 -*-
"""list2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LvZhuncyOsmwoFNVsd4XpAa-UbJo1lMZ
"""

list1 = [2,4,6,8,10]
for i in list1:
    print(i**2)

for i in list1:
    print(i**3)

